### PR TITLE
POI 4.1.2

### PR DESCRIPTION
**Pull request by ndevreeze**
Upgrade to POI 4.1.2. Also includes necessary upgrades of Clojure to 1.10.1 and Midje to 1.9.9, wrt working with Java 11.

Some more notes, not sure this is the right place (this is actually my first PR on Github):
I saw other forks (eg  joshuaeckroth/excel) with a newer (0.3.0) version, but decided to create a PR to the base/origin. I made some more changes in my own version: getting correct data types including (JSR 310) date/times and getting formatted values. Would like to know if you would be interested in this. It could mean some breaking changes and changing test cases.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Thanks for the PR! I'm happy to merge this and publish a new version to Clojars. I'll try to do that this week.

I haven't been using this library for a few years. You might be better off using your own fork (or someone else's). I could give you permissions on this repo to do more development, but I don't think that granting permissions on Clojars for just this project would be so easy.

**Comment by ndevreeze** [comment]
Thanks, glad you like it! I'll wait for your merge/publish and then probably continue with my own fork based on this. I agree that the Clojars permissions would be tricky, so I'll use my own group (ndevreeze) for next versions (probably starting with 3.1 since there's also a 3.0 version from joshuaeckroth). Anyway, thanks for creating the library, good to have it as a starting point for using the POI library.

**Comment by jamesaoverton** [comment]
I finally got around to this: https://clojars.org/ontodev/excel/versions/0.2.6

Thanks again!

**Comment by ndevreeze** [comment]
Hi, thanks for merging. In the meantime I added some more functionality to my own fork and also pushed to clojars. See https://github.com/ndevreeze/excel and https://clojars.org/ndevreeze/excel. Versioning is a bit of a mess, I created 0.3.1 for now. If you want, I can create another PR for this for your main branch. But if not (as discussed before), that's fine too.

**Pull request merged**
